android/app/google-services.json
- Just updated google json file so now it uses the hotfootdev account
=> 40 - Updated json file

lib/features/login/presentation/ui/widgets/login_form.dart
=> 53 - Login Keyboard Actions

lib/features/navigation_home/presentation/ui/widgets/run_card.dart, lib/features/runs/data/data_sources/runs_remote_data_source.dart, lib/features/runs/presentation/ui/screens/run_details_screen.dart, lib/features/runs/presentation/ui/widgets/run_form.dart
Fixes #81 
- Keep in mind that the user will not be able to edit the destination address. (This could be a problem).
- But we will think about that later
=> 81 - Allow customers to reorder past orders

lib/features/run_placed/presentation/ui/screen/run_placed_screen.dart, lib/features/run_placed/presentation/ui/widgets/chat_section.dart, lib/features/run_placed/presentation/ui/widgets/open_close_chat_button.dart
Takes the run model of the current run, and creates the unique chatroom using the customerid+runnerid
=> 85 - Creates unique chatroom from runmodel

lib/features/run_placed/presentation/ui/screen/run_placed_screen.dart, lib/features/run_placed/presentation/ui/widgets/cancel_delivery_button.dart, lib/features/runs/domain/entities/run_status.dart
- initial cancellation feature, updates the status of the run remotely
=> 87 - Now has a cancelled state for run

lib/features/runs/presentation/blocs/accept_run/accept_run_bloc.dart, lib/features/runs/presentation/blocs/accept_run/accept_run_event.dart, lib/features/runs/presentation/blocs/accept_run/accept_run_state.dart, lib/features/runs/presentation/ui/screens/accept_run_screen.dart, lib/injection_container.dart, pubspec.lock
Simply updates the status and runner id of the run
=> 76 - Simple accept run button

lib/features/registration/presentation/ui/widgets/registration_form.dart
- password error messages are now more verbose
=> 101 -  better error msgs for passwords

lib/features/runs/presentation/ui/widgets/run_card.dart, lib/features/runs/presentation/ui/widgets/run_list_tile.dart
=> 123 - Add photo to run cards

lib/features/runs/presentation/ui/screens/accept_run_screen.dart, lib/features/runs/presentation/ui/widgets/run_photo.dart
=> 125 - Add place photo to accept run screen

lib/features/runs/presentation/ui/screens/accept_run_screen.dart
Fixes #128
- @Mysdreivus This is how you can use the UserPhotoWidget
=> 128 - Add customer avatar to accept run screen

lib/features/registration/data/repositories/registration_repository_impl.dart, lib/features/user/domain/entities/user_entity.dart
- Now auto logs in upon registration within a 60 second window, timer can be adjusted, just want to make sure we aren't requesting too much too fast from firebase
=> 118 - auto login now possible

lib/features/user/data/data_sources/user_remote_data_source.dart
- Usermodel name parameter is from parsed email
=> 136 - now parses name parameter for usermodel

lib/features/runs/data/data_sources/runs_remote_data_source.dart
=> 141 - Forward Runner App to Active Run

lib/features/run_placed/presentation/ui/widgets/chat_message_list_item.dart, lib/features/run_placed/presentation/ui/widgets/chat_section.dart
- I just parsed where the name is parsed (it is now parsed before being pushed to the database rather than when the messagelist is being built)
=> 141 - changed where sender's name is parsed

lib/features/run_map/presentation/ui/widgets/user_details_popup.dart
=> 144 - Add avatar to user detail pop up

lib/features/login/presentation/ui/screen/login_screen.dart, lib/features/navigation_home/presentation/ui/widgets/home_tab.dart, lib/features/navigation_home/presentation/ui/widgets/runs_tab.dart, lib/features/registration/presentation/ui/screen/registration_screen.dart, lib/features/run_placed/presentation/ui/screen/run_placed_screen.dart, lib/features/run_placed/presentation/ui/widgets/chat_section.dart, lib/features/runs/presentation/ui/screens/accept_run_screen.dart, lib/features/runs/presentation/ui/screens/run_details_screen.dart, lib/features/search/presentation/ui/screens/search_handler_screen.dart, lib/features/search/presentation/ui/screens/unknown_place_screen.dart, lib/features/search/presentation/ui/widgets/search_bar.dart, lib/features/search/presentation/ui/widgets/search_bottom_drawer.dart, lib/features/user/presentation/ui/screens/settings_screen.dart
- ui tuneups for appbars and other areas where text is displayed
=> 147 - updated app bar fonts to match rest of app

lib/features/user/data/data_sources/user_local_data_source.dart, lib/features/user/presentation/ui/widgets/user_photo_widget.dart, lib/injection_container.dart
=> 147 - Get correct user id for photo

lib/features/user/data/repositories/user_repositories_impl.dart
=> 151 - Get photo from remote repo if possible

lib/features/user/presentation/ui/widgets/user_type_toggle_switch.dart
=> 153 - Toggle Switch Colors

lib/features/user/data/repositories/user_repositories_impl.dart
Reverts ZonalWings/hotfoot#152
Make user icon flicker too much. It's not like we'll be changing our iamges in the middle of the presentation anyways
=> Revert "151 - Get photo from remote repo if possible"
